package EAD;

import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import javax.swing.SwingConstants;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.scilab.forge.jlatexmath.TeXConstants;
import org.scilab.forge.jlatexmath.TeXFormula;
import org.scilab.forge.jlatexmath.TeXIcon;

/**
 *
 * @author hugoocampo
 */
public class PruebaLatex1 extends javax.swing.JFrame {

    /**
     * Creates new form PruebaLatex1
     */
    public PruebaLatex1() {
        initComponents();
        escribirEnPane();
        escribirEnLabel();
    }

    public void escribirEnPane() {

        try {
            
            String texto1 = String.format("\\text{Metodo numericos}");
            String texto2 = String.format("\\text{Formula para calcular el área:}");
            String texto3 = String.format("A=\\pi r^2");
            String texto4 = String.format("\\text{Fórmula para calcular el perímetro:}");
            String texto5 = String.format("P=\\pi \\cdot D");
            textoLatexPane(jTxPaneContenido, texto1);
            textoLatexPane(jTxPaneContenido, texto2);
            textoLatexPane(jTxPaneContenido, texto3);
            textoLatexPane(jTxPaneContenido, texto4);
            textoLatexPane(jTxPaneContenido, texto5);
        } catch (BadLocationException ex) {
            Logger.getLogger(PruebaLatex1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void escribirEnLabel() {
        String texto1 = String.format("A=\\pi r^2");
        textoLatexLabel(jLbFormula, texto1);

    }

    public static void textoLatexPane(JTextPane textPane, String latex) throws BadLocationException {
// Crear fórmula y renderizar el ícono
        TeXFormula formula = new TeXFormula(latex);
        TeXIcon icon = formula.createTeXIcon(TeXFormula.SERIF, 18);
// Crear una imagen con fondo transparente
        BufferedImage image = new BufferedImage(
                icon.getIconWidth(),
                icon.getIconHeight(),
                BufferedImage.TYPE_INT_ARGB
        );
        icon.paintIcon(null, image.getGraphics(), 0, 0);
// Convertir la imagen a un ImageIcon
        ImageIcon latexIcon = new ImageIcon(image);
// Obtener o crear el estilo
        StyledDocument doc = textPane.getStyledDocument();
        Style style = textPane.getStyle("LaTeXStyle");
        if (style == null) {
            style = textPane.addStyle("LaTeXStyle", null);
        }
        StyleConstants.setIcon(style, latexIcon);
// Insertar imagen y salto de línea
        doc.insertString(doc.getLength(), " ", style);
        doc.insertString(doc.getLength(), "\n\n", null);
// Opcional: desplazarse automáticamente al final
        textPane.setCaretPosition(doc.getLength());
// Opcional: proteger edición del usuario
        textPane.setEditable(false);
    }

    private void textoLatexLabel(JLabel jLb, String latex) {
        TeXFormula formula = new TeXFormula(latex);
// Crear el ícono con tamaño (20 es un buen punto de partida)
        TeXIcon icon = formula.createTeXIcon(TeXConstants.STYLE_DISPLAY, 22);
//icon.setInsets(new Insets(5, 5, 2, 2)); // top, left, bottom, right
// Asignar ícono al JLabel que agregaste desde el diseñador
        jLb.setIcon(icon);
// Eliminar texto si tenía algo
        jLb.setText(null);
//Alinear la imagen
        jLb.setHorizontalAlignment(SwingConstants.CENTER);
        jLb.setVerticalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLbFormula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxPaneContenido = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PRUEBAS CON LATEX");

        jLbFormula.setText("SABADO");

        jScrollPane1.setViewportView(jTxPaneContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLbFormula))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLbFormula)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaLatex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaLatex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaLatex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaLatex1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaLatex1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbFormula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTxPaneContenido;
    // End of variables declaration//GEN-END:variables
}
